version: 2
jobs:
  build:
    docker:
      - image: php:7.0-apache
    working_directory: .
    steps:
      - checkout
      - run:
          name: Install Mina
          command: |
            apt-get update
            apt-get install ruby -y
            gem install mina mina-rsync
      - deploy:
          name: Deploy to JordyBoothy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              ls -lah
              pwd
              mina deploy
            fi

