version: 2
jobs:
  build:
    docker:
      - image: php:7.0-apache
    working_directory: .
    steps:
      - checkout
      - run:
          name: Install Mina
          command: |
            apt-get update
            apt-get install ruby ssh -y
            gem install mina -v 0.3.8
      - deploy:
          name: Deploy to JordyBoothy
          command: |
            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              mina deploy
            fi

